### ISSUE TITLE
add_children() doesn't have an effect on actual Notion

### ISSUE THREAD

**Issue by 4tires** [AlbertoMartinPerez/Notion_API_SDK#1]
Hello,

I am probably making a mistake, if you could help me spot it, I would be very thankful.

So, I'm using add_children to add blocks but it only changes my object, not the actual Notion block:

```
Learning = notion.blocks.retrieve(block_id)
add_children(parent=Learning, children=to_do(checked=True, content='test'))
```

Do you know what I'm doing wrong? No messages of error appeared.

**Comment by AlbertoMartinPerez** [comment]
Hello Paulo!

`add_children()` **does not** change the Notion block. It adds a children to a Python object, in this case, the block you pass as `parent` parameter.

In your case, the `add_children()` adds a _to_do_ block to the Python dictionary stored in your `Learning` variable. Once you have updated that dictionary, you then **need to upload it using the Notion API**.

I have pushed some examples for you to see how to upload blocks a Notion page. Please `blocks_example.py` to see how to append multiple blocks to a Notion API after using `add_children()`

**Comment by 4tires** [comment]
Muchas gracias Alberto! I've managed to do it!
